import InteractiveFlowchart from "./InteractiveFlowchart";
import { StartNode, DecisionNode, Arrow, Branch, OutcomeCard, TwoWaySplit } from "./FlowchartElements";
import { HelpCircle, Check, X, GitBranch, Lightbulb } from 'lucide-react';

export default function Chapter19() {
  return (
    <div className="prose prose-slate max-w-none prose-headings:text-[#0f172a] prose-p:text-slate-600 prose-li:text-slate-700">
      
      <div className="bg-blue-50 border-l-4 border-blue-600 p-5 my-6 rounded-r-lg shadow-sm not-prose">
        <h2 className="text-xl font-bold text-blue-900 mt-0 mb-2">Rule (xii): Active Therapeutic Medical Devices for Administering or Exchanging Energy</h2>
        <p className="m-0 font-medium text-blue-800 italic">
          "Classifying active (powered) devices that transfer heat, electricity, light, or radiation to a patient under Indian MDR 2017"
        </p>
      </div>

      <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 mb-8">
        <h3 className="text-lg font-bold text-slate-800 mt-0 mb-3">Learning Objectives</h3>
        <p className="mb-2">After studying this chapter, you will be able to:</p>
        <ul className="mt-0 mb-0 space-y-1">
          <li>Define "active medical device" and understand therapeutic energy transfer.</li>
          <li>Distinguish the 3 key subparts of Rule (xii): <strong>Subparts (a) to (c)</strong>.</li>
          <li>Explain why a standard muscle stimulator is Class B, while surgical lasers and ventilators escalate to Class C.</li>
          <li>Understand why controllers of Class C active therapeutic systems also become Class C.</li>
        </ul>
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2">
        <HelpCircle className="w-6 h-6 text-indigo-500" /> 
        19.1 What Is an Active Therapeutic Device?
      </h3>
      <p>
        An <strong>active medical device</strong> relies on electrical, pneumatic, or mechanical energy (not generated by gravity or the human body) to function. A therapeutic active device actively transfers or exchanges this energy to treat, alleviate, or cure illness or injury.
      </p>

      <h3 className="text-xl font-semibold mt-8 mb-3">19.2 Detailed Explanation of Subparts</h3>
      
      <div className="space-y-6">
        {/* Subpart (a) */}
        <div className="border border-amber-200 rounded-xl p-6 bg-amber-50/50">
          <div className="flex justify-between items-start mb-2">
            <h4 className="text-amber-950 font-bold text-lg m-0">Subpart (a) &rarr; Class B (Low-Moderate Risk)</h4>
            <span className="bg-amber-600 text-white font-bold text-xs px-3 py-1 rounded-full">Class B</span>
          </div>
          <p className="text-sm font-semibold text-amber-900 mt-1 mb-2">Criteria:</p>
          <p className="text-sm text-slate-700 m-0 bg-white p-3 rounded border border-amber-100">
            Subject to subpart (b), active therapeutic devices intended for administering or exchanging energy to or with a human body.
          </p>
          <p className="text-sm font-semibold text-amber-900 mt-3 mb-1">Key Concept:</p>
          <p className="text-sm text-slate-700 m-0">
            Low-density energy transfer that carries minimal risk of deep tissue destruction, shock, or immediate systemic failure.
          </p>
          <p className="text-sm font-semibold text-amber-900 mt-3 mb-1">Examples:</p>
          <ul className="text-sm text-slate-700 grid sm:grid-cols-2 gap-1 m-0">
            <li>Electrical muscle stimulators (EMS)</li>
            <li>Transcutaneous Electrical Nerve Stimulation (TENS) units</li>
            <li>Infrared phototherapy heating lamps</li>
            <li>Blue light phototherapy units (infant jaundice)</li>
          </ul>
        </div>

        {/* Subpart (b) */}
        <div className="border border-red-200 rounded-xl p-6 bg-red-50/50">
          <div className="flex justify-between items-start mb-2">
            <h4 className="text-red-950 font-bold text-lg m-0">Subpart (b) &rarr; Class C (Moderate-High Risk)</h4>
            <span className="bg-red-600 text-white font-bold text-xs px-3 py-1 rounded-full">Class C</span>
          </div>
          <p className="text-sm font-semibold text-red-900 mt-1 mb-2">Criteria:</p>
          <p className="text-sm text-slate-700 m-0 bg-white p-3 rounded border border-red-100">
            If the administration or exchange of energy may be done in a potentially hazardous way (e.g., emission of ionizing radiation), taking into account the nature, density, site of application of the energy, and the technology involved.
          </p>
          <p className="text-sm font-semibold text-red-900 mt-3 mb-1">Key Concept:</p>
          <p className="text-sm text-slate-700 m-0">
            High energy densities or vital organ administration. High frequency currents can burn tissues, lasers cut cells, and ventilator failures can suffocate patients immediately.
          </p>
          <p className="text-sm font-semibold text-red-900 mt-3 mb-1">Examples:</p>
          <ul className="text-sm text-slate-700 grid sm:grid-cols-2 gap-1 m-0">
            <li>Radiotherapy linear accelerators (ionizing radiation)</li>
            <li>Surgical cutting lasers</li>
            <li>High-frequency electrosurgical generators (diathermy)</li>
            <li>Mechanical ICU ventilators</li>
            <li>External cardiac defibrillators</li>
          </ul>
        </div>

        {/* Subpart (c) */}
        <div className="border border-red-200 rounded-xl p-6 bg-red-50/50">
          <div className="flex justify-between items-start mb-2">
            <h4 className="text-red-950 font-bold text-lg m-0">Subpart (c) &rarr; Class C (Moderate-High Risk)</h4>
            <span className="bg-red-600 text-white font-bold text-xs px-3 py-1 rounded-full">Class C</span>
          </div>
          <p className="text-sm font-semibold text-red-900 mt-1 mb-2">Criteria:</p>
          <p className="text-sm text-slate-700 m-0 bg-white p-3 rounded border border-red-100">
            If intended for the control or monitoring, or used to directly influence the performance, of a Class C active therapeutic device.
          </p>
          <p className="text-sm font-semibold text-red-900 mt-3 mb-1">Key Concept:</p>
          <p className="text-sm text-slate-700 m-0">
            Controllers and programmer consoles are the "brains" of the therapeutic delivery. If the console miscalculates, the treatment machine will deliver incorrect, dangerous dosages. Hence, they are classed with the device they control.
          </p>
          <p className="text-sm font-semibold text-red-900 mt-3 mb-1">Examples:</p>
          <ul className="text-sm text-slate-700 grid sm:grid-cols-2 gap-1 m-0">
            <li>Control consoles for radiotherapy equipment</li>
            <li>External programmers for implantable pacemakers</li>
          </ul>
        </div>
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><GitBranch className="w-6 h-6 text-emerald-600"/> 19.3 Rule (xii) Decision Flow</h3>
      <InteractiveFlowchart minHeight="350px">
        <div className="flex flex-col items-center w-full">
          <StartNode text="Active Therapeutic Device" />
          <Arrow />
          <DecisionNode text="Is energy exchanged in a potentially hazardous way (ionizing, high density, surgical lasers, ICU vents)?" />
          
          <TwoWaySplit
            leftLabel="YES"
            rightLabel="NO"
            leftChild={
              <OutcomeCard
                clazz="C"
                subpart="Subpart (b)"
                title="Class C - High Risk Energy exchange"
                examples={["Surgical cutting lasers", "Electrosurgical generators"]}
              />
            }
            rightChild={
              <div className="flex flex-col items-center w-full">
                <DecisionNode text="Does it control or monitor a Class C Active Therapeutic Device?" />
                <TwoWaySplit
                  leftLabel="YES"
                  rightLabel="NO"
                  leftChild={
                    <OutcomeCard
                      clazz="C"
                      subpart="Subpart (c)"
                      title="Class C - Controller Module"
                      examples={["Pacemaker external programmer console", "Laser software monitors"]}
                    />
                  }
                  rightChild={
                    <OutcomeCard
                      clazz="B"
                      subpart="Subpart (a)"
                      title="Class B - Standard Energy exchange"
                      examples={["Muscle stimulators", "TENS pain relief units"]}
                    />
                  }
                />
              </div>
            }
          />
        </div>
      </InteractiveFlowchart>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><Lightbulb className="w-6 h-6 text-amber-500"/> 19.4 Practice Quiz</h3>
      <div className="border border-slate-200 rounded-lg p-5 bg-slate-50">
        <p className="font-semibold text-slate-800 m-0 mb-3">Which class is correct for a clinical surgical CO2 cutting laser under Indian MDR 2017?</p>
        <div className="flex flex-col gap-2">
          <div className="p-3 bg-white border border-slate-200 rounded-lg flex justify-between items-center text-sm">
            <span>Class B - standard phototherapy</span>
            <X className="w-5 h-5 text-red-500" />
          </div>
          <div className="p-3 bg-white border border-emerald-500 bg-emerald-50 rounded-lg flex justify-between items-center text-sm font-medium text-emerald-950">
            <span>Class C (Subpart b - energy exchanged in a potentially hazardous way)</span>
            <Check className="w-5 h-5 text-emerald-600" />
          </div>
        </div>
      </div>

      <div className="not-prose bg-slate-800 text-white rounded-xl p-6 my-8">
        <h3 className="text-xl font-bold text-blue-400 mt-0 mb-4">Chapter Summary</h3>
        <ul className="text-slate-200 space-y-2 mb-6 m-0 pl-4 list-disc">
          <li><strong>Subpart (a)</strong> = Class B: Mild therapeutic energy transfer (TENS, heat lamps).</li>
          <li><strong>Subpart (b)</strong> = Class C: High-hazard energy exchange (lasers, radiotherapy, ventilators, defibrillators).</li>
          <li><strong>Subpart (c)</strong> = Class C: Control systems or vital programmers governing Class C active therapeutic units.</li>
        </ul>
      </div>

    </div>
  );
}
