import InteractiveFlowchart from "./InteractiveFlowchart";
import { StartNode, DecisionNode, Arrow, Branch, OutcomeCard, TwoWaySplit, MultiSplit } from "./FlowchartElements";
import { ArrowDown, CornerDownRight, Zap, Activity, ShieldAlert, AlertCircle, GitBranch, Lightbulb, Monitor, Thermometer } from 'lucide-react';

export default function Chapter15() {
  return (
    <div className="prose prose-slate max-w-none prose-headings:text-[#0f172a] prose-p:text-slate-600 prose-li:text-slate-700">
      
      <div className="bg-blue-50 border-l-4 border-blue-600 p-5 my-6 rounded-r-lg shadow-sm not-prose">
        <h2 className="text-xl font-bold text-blue-900 mt-0 mb-2">PART IV: ACTIVE MEDICAL DEVICES</h2>
        <h2 className="text-xl font-bold text-blue-900 mt-0 mb-2">Chapter 15: Understanding Active Medical Devices</h2>
        <p className="m-0 font-medium text-blue-900 italic">
          "A Device That Uses Energy Can Create New Types of Risk"
        </p>
      </div>

      <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 mb-8">
        <h3 className="text-lg font-bold text-slate-800 mt-0 mb-3">Learning Objectives</h3>
      <div className="my-6 rounded-xl overflow-hidden shadow-md">
        <img src="https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=1200&q=80" alt="Medical concept illustration" className="w-full h-64 object-cover" />
      </div>

        <p className="mb-2">After studying this chapter, you will be able to:</p>
        <ul className="mt-0 mb-0 space-y-1">
          <li>Understand what an Active Medical Device is.</li>
          <li>Learn why electricity changes the classification approach.</li>
          <li>Understand different forms of medical energy.</li>
          <li>Learn the difference between Active and Non-Active Devices.</li>
          <li>Understand Active Therapeutic Devices.</li>
          <li>Understand Active Diagnostic Devices.</li>
          <li>Learn combination active devices.</li>
          <li>Understand why software becomes important.</li>
          <li>Learn how regulators think before applying Rules 9–12.</li>
        </ul>
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.1 We Are Entering a New World</h3>
      <p>Until now, we have classified devices mainly by asking: Does it enter the body? How long does it stay? Does it become an implant?</p>
      <p>Now, those questions are no longer enough. Imagine two devices.</p>
      
      <div className="grid sm:grid-cols-2 gap-4 my-6">
        <div className="border border-slate-200 rounded-lg p-5 bg-white shadow-sm">
          <h5 className="font-bold text-slate-800 mb-2 mt-0 text-lg">Device A</h5>
          <p className="text-sm text-slate-600 mb-0">A wheelchair.</p>
        </div>
        <div className="border border-slate-200 rounded-lg p-5 bg-white shadow-sm">
          <h5 className="font-bold text-slate-800 mb-2 mt-0 text-lg">Device B</h5>
          <p className="text-sm text-slate-600 mb-2">An electric wheelchair.</p>
          <p className="text-sm text-slate-600 mb-0">They look almost identical. Both help patients move. Yet, the electric wheelchair has: batteries, electric motors, charging systems, electronic controls, software, sensors.</p>
        </div>
      </div>
      
      <p className="font-medium text-rose-700">Suddenly, many new risks appear. That is why MDR 2017 separates Active Medical Devices from many of the earlier rules.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><Zap className="w-6 h-6 text-amber-500" /> 15.2 What Is an Active Medical Device?</h3>
      <p>An <strong>Active Medical Device</strong> is a medical device that requires an external source of energy to perform its intended medical function.</p>
      <p>The energy may come from: electricity, batteries, compressed gas, electromagnetic energy, other external energy sources.</p>
      <p className="font-medium text-slate-800">The MDR 2017 defines an active medical device as one whose operation depends on electrical energy or another source of energy other than that generated by the human or animal body or gravity.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.3 Everyday Analogy</h3>
      <p>Imagine two bicycles. One is an ordinary bicycle. It moves because you pedal. No electricity.</p>
      <p>The second bicycle uses: battery, electric motor, controller.</p>
      <p className="font-semibold text-slate-800">Now, if the battery fails, the bicycle behaves differently. The electrical system introduces completely new risks. Medical devices work exactly the same way.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.4 Active vs Non-Active Devices</h3>
      <div className="overflow-x-auto my-6">
        <table className="min-w-full border-collapse border border-slate-200 text-sm">
          <thead>
            <tr className="bg-slate-100">
              <th className="border border-slate-200 px-4 py-2 text-left font-semibold text-slate-800">Non-Active Device</th>
              <th className="border border-slate-200 px-4 py-2 text-left font-semibold text-slate-800">Active Device</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border border-slate-200 px-4 py-2">Scalpel</td>
              <td className="border border-slate-200 px-4 py-2">Electrosurgical Unit</td>
            </tr>
            <tr>
              <td className="border border-slate-200 px-4 py-2">Syringe</td>
              <td className="border border-slate-200 px-4 py-2">Infusion Pump</td>
            </tr>
            <tr>
              <td className="border border-slate-200 px-4 py-2">Manual Wheelchair</td>
              <td className="border border-slate-200 px-4 py-2">Powered Wheelchair</td>
            </tr>
            <tr>
              <td className="border border-slate-200 px-4 py-2">Manual Suction Device</td>
              <td className="border border-slate-200 px-4 py-2">Electric Suction Machine</td>
            </tr>
            <tr>
              <td className="border border-slate-200 px-4 py-2">Glass Thermometer</td>
              <td className="border border-slate-200 px-4 py-2">Digital Thermometer</td>
            </tr>
            <tr>
              <td className="border border-slate-200 px-4 py-2">Manual Blood Pressure Apparatus</td>
              <td className="border border-slate-200 px-4 py-2">Automatic Blood Pressure Monitor</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p>Notice something. Both devices perform similar medical functions.</p>
      <p className="font-bold text-indigo-700 bg-indigo-50 p-3 rounded inline-block">The difference lies in how they perform the function.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.5 Where Does the Energy Come From?</h3>
      <p>Many beginners think <em>Active</em> means <em>Electricity</em>. Actually, many different energy sources exist. Examples include:</p>
      
      <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 my-6">
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Electrical Energy</h5>
           <ul className="text-sm m-0 space-y-1">
             <li>ECG Machine</li>
             <li>Ventilator</li>
             <li>MRI</li>
           </ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Battery Power</h5>
           <ul className="text-sm m-0 space-y-1">
             <li>Pacemaker</li>
             <li>Infusion Pump</li>
             <li>Hearing Aid</li>
           </ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Compressed Gas</h5>
           <ul className="text-sm m-0 space-y-1">
             <li>Ventilator</li>
             <li>Anaesthesia Machine</li>
           </ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Ultrasound Energy</h5>
           <ul className="text-sm m-0 space-y-1"><li>Ultrasound Scanner</li></ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Laser Energy</h5>
           <ul className="text-sm m-0 space-y-1"><li>Laser Surgical System</li></ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Radiofrequency Energy</h5>
           <ul className="text-sm m-0 space-y-1"><li>RF Ablation System</li></ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Microwave Energy</h5>
           <ul className="text-sm m-0 space-y-1"><li>Certain therapeutic devices</li></ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Light Energy</h5>
           <ul className="text-sm m-0 space-y-1"><li>Phototherapy Devices</li></ul>
        </div>
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
           <h5 className="font-bold text-slate-800 mt-0 mb-2">Magnetic Energy</h5>
           <ul className="text-sm m-0 space-y-1"><li>MRI Scanner</li></ul>
        </div>
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><ShieldAlert className="w-6 h-6 text-rose-500" /> 15.6 Why Does Electricity Increase Risk?</h3>
      <p>Imagine holding a kitchen knife. Now imagine holding an electric saw. Both cut. But the electric saw moves faster, produces more power, and can cause more severe injury if it malfunctions.</p>
      <p>The same principle applies to medical devices. Electrical systems introduce risks such as:</p>
      <ul className="grid sm:grid-cols-2 gap-2 mb-4">
        <li>electric shock,</li>
        <li>overheating,</li>
        <li>battery failure,</li>
        <li>software failure,</li>
        <li>sensor failure,</li>
        <li>electromagnetic interference,</li>
        <li>power interruption.</li>
      </ul>
      <p className="font-medium text-rose-700">These risks did not exist with purely mechanical devices.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.7 What Happens If the Power Fails?</h3>
      <p>Imagine an examination table. If the electricity fails, nothing much happens.</p>
      <p>Now imagine a ventilator. If electrical power fails while a patient depends on it, the consequences may be life-threatening.</p>
      <p className="font-semibold text-slate-800">This is why not every active device has the same level of risk. The clinical importance of the function is just as important as the energy source.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><Activity className="w-6 h-6 text-emerald-500" /> 15.8 Active Therapeutic Devices</h3>
      <p>Some active devices <strong>treat patients</strong>.</p>
      <div className="bg-emerald-50 border border-emerald-200 p-5 my-6 rounded-xl shadow-sm"><strong className="text-emerald-800 flex items-center gap-2 text-lg">📝 Example</strong><p className="mt-2 mb-0 text-emerald-700">include: Ventilator, Defibrillator, Dialysis Machine, Electrosurgical Unit, Therapeutic Laser, Infusion Pump.</p></div>
      <p className="font-bold text-emerald-700">These devices actively change the patient's condition.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><Monitor className="w-6 h-6 text-blue-500" /> 15.9 Active Diagnostic Devices</h3>
      <p>Other active devices <strong>do not provide treatment</strong>. Instead, they collect information.</p>
      <div className="bg-emerald-50 border border-emerald-200 p-5 my-6 rounded-xl shadow-sm"><strong className="text-emerald-800 flex items-center gap-2 text-lg">📝 Example</strong><p className="mt-2 mb-0 text-emerald-700">include: ECG Machine, EEG Machine, CT Scanner, MRI Scanner, Ultrasound Scanner, Digital X-Ray, Patient Monitor.</p></div>
      <p className="font-bold text-blue-700">Their purpose is diagnosis, monitoring, or clinical decision-making.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.10 Active Monitoring Devices</h3>
      <p>Some devices continuously observe the patient's condition.</p>
      <div className="bg-emerald-50 border border-emerald-200 p-5 my-6 rounded-xl shadow-sm"><strong className="text-emerald-800 flex items-center gap-2 text-lg">📝 Example</strong><p className="mt-2 mb-0 text-emerald-700">include: ICU Patient Monitor, Pulse Oximeter, Fetal Monitor, Holter ECG, Continuous Glucose Monitor.</p></div>
      <p className="font-medium text-slate-800">If these devices provide incorrect information, clinical decisions may be affected.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.11 Software Becomes a Medical Device</h3>
      <p>Modern medical devices often include software. Sometimes, the software itself is the medical device.</p>
      <p>Imagine an application that simply stores patient names. That is not performing a medical function.</p>
      <p>Now imagine software that analyses ECG data and helps detect arrhythmias. Here, the software contributes directly to diagnosis.</p>
      <p className="font-semibold text-slate-800">Its intended medical purpose brings it within the regulatory framework for medical devices. This is why software has become an important part of modern medical device regulation.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.12 Combination Active Devices</h3>
      <p>Many modern devices combine several technologies.</p>
      <div className="bg-emerald-50 border border-emerald-200 p-5 my-6 rounded-xl shadow-sm"><strong className="text-emerald-800 flex items-center gap-2 text-lg">📝 Example</strong><p className="mt-2 mb-0 text-emerald-700">Ventilator. Contains: air pump, pressure sensors, oxygen sensors, software, alarms, battery, display, valves, control system.</p></div>
      <p>To the patient, it looks like one machine. To the regulator, it is a complex system made of many interacting components.</p>
      <p className="font-medium text-slate-800">The device must still be assessed as a whole according to its intended medical purpose.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3">15.13 Why Active Devices Need Additional Standards</h3>
      <p>Because active devices use energy, they must also demonstrate electrical safety, electromagnetic compatibility, software reliability, and other performance characteristics.</p>
      <div className="bg-emerald-50 border border-emerald-200 p-5 my-6 rounded-xl shadow-sm"><strong className="text-emerald-800 flex items-center gap-2 text-lg">📝 Example</strong><p className="mt-2 mb-0 text-emerald-700">of widely used international standards include:</p></div>
      <ul className="mb-4">
        <li><strong>IEC 60601 series</strong> (electrical medical equipment safety and performance)</li>
        <li><strong>IEC 62304</strong> (medical device software lifecycle)</li>
        <li><strong>IEC 62366-1</strong> (usability engineering)</li>
      </ul>
      <p className="font-medium text-slate-800">These standards complement the regulatory framework by helping manufacturers demonstrate that the device performs safely and as intended.</p>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><AlertCircle className="w-6 h-6 text-amber-500"/> 15.14 Common Beginner Mistakes</h3>
      <div className="space-y-4 my-6">
        <div className="border border-slate-200 rounded-lg p-4 bg-white shadow-sm">
          <p className="font-bold text-red-600 m-0 mb-1">Mistake 1: "Every electrical product is a medical device."</p>
          <p className="text-sm text-slate-600 m-0"><strong className="text-green-600">Correction:</strong> Incorrect. A household fan uses electricity. It is not intended for a medical purpose. Therefore, it is not a medical device.</p>
        </div>
        <div className="border border-slate-200 rounded-lg p-4 bg-white shadow-sm">
          <p className="font-bold text-red-600 m-0 mb-1">Mistake 2: "Every medical device using electricity belongs to the same class."</p>
          <p className="text-sm text-slate-600 m-0"><strong className="text-green-600">Correction:</strong> Incorrect. A digital thermometer and a ventilator both use electricity, yet they perform very different medical functions.</p>
        </div>
        <div className="border border-slate-200 rounded-lg p-4 bg-white shadow-sm">
          <p className="font-bold text-red-600 m-0 mb-1">Mistake 3: "Software is never a medical device."</p>
          <p className="text-sm text-slate-600 m-0"><strong className="text-green-600">Correction:</strong> Incorrect. Software intended for diagnosis, monitoring, or treatment may itself be regulated as a medical device.</p>
        </div>
        <div className="border border-slate-200 rounded-lg p-4 bg-white shadow-sm">
          <p className="font-bold text-red-600 m-0 mb-1">Mistake 4: "Large machines are always higher class."</p>
          <p className="text-sm text-slate-600 m-0"><strong className="text-green-600">Correction:</strong> Incorrect. Classification still depends on intended use and the applicable rules, not simply on size or complexity.</p>
        </div>
      </div>

      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><GitBranch className="w-6 h-6 text-emerald-600"/> 15.15 Decision Tree</h3>
      <InteractiveFlowchart minHeight="450px">
        <div className="flex flex-col items-center min-w-max">
          <StartNode text="Device Assessment" />
          <Arrow />
          <DecisionNode text="Does it require an external source of energy to perform its intended medical function?" />
          
          <TwoWaySplit
            leftLabel="NO"
            rightLabel="YES"
            leftChild={
              <div className="bg-emerald-50 border-2 border-emerald-400 text-emerald-950 p-4 rounded-xl font-bold text-center max-w-[200px] text-xs shadow-sm">
                Non-Active Devices (Rules i - viii) &rarr; See Non-Active Sections
              </div>
            }
            rightChild={
              <MultiSplit
                branches={[
                  {
                    label: "Therapeutic / Energy Admin (Rule ix)",
                    child: (
                      <OutcomeCard
                        clazz="C"
                        subpart="Rule ix"
                        title="Active Therapeutic"
                        examples={["Infusion pumps", "Defibrillators: Class D"]}
                      />
                    )
                  },
                  {
                    label: "Diagnostic / Monitoring (Rule x)",
                    child: (
                      <OutcomeCard
                        clazz="B"
                        subpart="Rule x - xii"
                        title="Active Diagnostic / Administration"
                        examples={["Ultrasound: Class C", "MRI: Class C", "Digital Thermometers"]}
                      />
                    )
                  }
                ]}
              />
            }
          />
        </div>
      </InteractiveFlowchart>
      <h3 className="text-xl font-semibold mt-8 mb-3 flex items-center gap-2"><Lightbulb className="w-6 h-6 text-amber-500"/> 15.16 Memory Trick</h3>
      <div className="bg-amber-50 border border-amber-200 p-5 rounded-lg my-6 text-center">
        <p className="text-sm text-amber-800 m-0 mb-3">Imagine two flashlights. One is a simple torch. The other is a powerful laser. Both produce light.</p>
        <p className="text-sm text-amber-800 m-0 mb-3">But one simply illuminates, while the other can cut metal or tissue. The energy source alone does not determine risk. How that energy is used determines the level of risk.</p>
        <p className="text-lg font-bold text-amber-900 m-0 italic">Remember: "Active devices use energy. Regulators ask what that energy does to the patient."</p>
      </div>

      <div className="not-prose bg-slate-800 text-white rounded-xl p-6 my-8">
        <h3 className="text-xl font-bold text-blue-400 mt-0 mb-4">Chapter Summary</h3>
        <p className="text-slate-300 text-sm mb-4">By the end of this chapter, you should understand:</p>
        <ul className="text-slate-200 space-y-2 mb-6">
          <li>An <strong>Active Medical Device</strong> depends on an external source of energy to perform its intended medical function.</li>
          <li>Active devices may use electricity, batteries, compressed gas, ultrasound, laser, radiofrequency, magnetic fields, or other forms of energy.</li>
          <li>Active devices may be: Therapeutic (they treat), Diagnostic (they diagnose), Monitoring (they observe), Combination systems (they perform multiple functions).</li>
          <li>Software can itself be a medical device when it has an intended medical purpose.</li>
          <li>Before applying Rules 9–12, always ask: Does the device use external energy? What type of energy? What medical function does it perform? What could happen if that function fails?</li>
        </ul>

        <div className="bg-slate-700 p-4 rounded-lg border border-slate-600">
           <h4 className="font-bold text-blue-400 mt-0 mb-2">Preview of the Next Chapter</h4>
           <p className="text-sm text-slate-300 m-0 mb-2">In Chapter 16, we will begin <strong>Rule 9</strong>, which deals with <strong>active therapeutic medical devices</strong>.</p>
           <p className="text-sm text-slate-300 m-0 mb-2">We'll explore devices such as: Ventilators, Infusion pumps, Dialysis machines, Electrosurgical units, Therapeutic lasers, Defibrillators.</p>
           <p className="text-sm font-bold text-blue-900 m-0">We will explain why delivering energy into the human body changes the entire regulatory perspective. This is one of the most clinically important rules in the Medical Devices Rules, 2017.</p>
        </div>
      </div>

    </div>
  );
}
