import { useState, useEffect } from 'react';
import { X, Book, Loader2 } from 'lucide-react';

interface WordMeaningPopupProps {
  term: string;
  context: string;
  position: { x: number; y: number } | null;
  onClose: () => void;
}

const LOCAL_GLOSSARY: Record<string, { category: string; definition: string; examples: string[] }> = {
  "essential part": {
    category: "REGULATORY",
    definition: "An indispensable component or sub-assembly of a medical device without which the device cannot perform its intended therapeutic or diagnostic medical function.",
    examples: ["A laser diode within an ophthalmic photo-coagulator.", "The software algorithm in an automated external defibrillator."]
  },
  "active device": {
    category: "DEVICE TYPE",
    definition: "Any medical device whose operation depends on a source of electrical energy or any source of power other than that generated by the human body or gravity.",
    examples: ["Battery-powered pacemakers.", "Electric syringe pumps.", "Ultrasonic imaging systems."]
  },
  "active": {
    category: "DEVICE TYPE",
    definition: "A category of medical devices dependent on electrical or other non-manual power sources to perform their main therapeutic or diagnostic function.",
    examples: ["Ventilators.", "Infusion pumps."]
  },
  "invasive device": {
    category: "DEVICE TYPE",
    definition: "A medical device which, in whole or in part, penetrates inside the body, either through a body orifice or through the surface of the body.",
    examples: ["Endoscopes.", "Surgical needles.", "Urethral catheters."]
  },
  "invasive": {
    category: "DEVICE TYPE",
    definition: "Surgical or anatomical penetration of the body's natural boundaries, either via natural orifices or surgical incision.",
    examples: ["Invasive catheters.", "Surgical forceps."]
  },
  "surgically invasive": {
    category: "DEVICE TYPE",
    definition: "An invasive device which penetrates inside the body through the surface of the body, with the aid or in the context of a surgical operation.",
    examples: ["Surgical scalpels.", "Orthopedic bone screws.", "Surgical gloves."]
  },
  "implantable device": {
    category: "DEVICE TYPE",
    definition: "Any device intended to be totally introduced into the human body or to replace an epithelial surface or the surface of the eye by surgical intervention, and intended to remain in place after the procedure.",
    examples: ["Intraocular lenses.", "Artificial hip joints.", "Cardiac pacemakers."]
  },
  "implantable": {
    category: "DEVICE TYPE",
    definition: "Designed to be surgically placed permanently or semi-permanently within a living tissue or organ system.",
    examples: ["Suture anchors.", "Breast implants."]
  },
  "implanted": {
    category: "DEVICE TYPE",
    definition: "The state of a device having been surgically introduced and left within the body to serve its intended clinical purpose.",
    examples: ["Implanted neurostimulator.", "Implanted drug delivery port."]
  },
  "transient use": {
    category: "DURATION",
    definition: "Normally intended for continuous use for less than 60 minutes.",
    examples: ["Surgical gloves.", "Disposable syringes used for immediate injection.", "Transient catheters."]
  },
  "transient": {
    category: "DURATION",
    definition: "A short exposure or contact time of less than 60 minutes.",
    examples: ["Transient surgical instruments."]
  },
  "short-term use": {
    category: "DURATION",
    definition: "Normally intended for continuous use for between 60 minutes and 30 days.",
    examples: ["Temporary urinary catheters.", "Contact lenses.", "Suture needles."]
  },
  "short-term": {
    category: "DURATION",
    definition: "Continuous clinical exposure between 60 minutes and 30 days.",
    examples: ["Short-term wound dressings."]
  },
  "long-term use": {
    category: "DURATION",
    definition: "Normally intended for continuous use for more than 30 days.",
    examples: ["Orthopedic plates.", "Heart valves.", "Dental implants."]
  },
  "long-term": {
    category: "DURATION",
    definition: "Continuous clinical exposure exceeding 30 days.",
    examples: ["Long-term surgical implants."]
  },
  "reusable surgical instrument": {
    category: "DEVICE TYPE",
    definition: "An instrument intended for surgical use (cutting, drilling, sawing, scraping, clamping) without connection to any active device, which can be reused after appropriate cleaning/sterilization.",
    examples: ["Surgical scalpels handles.", "Surgical forceps.", "Reusable surgical scissors."]
  },
  "reusable": {
    category: "DEVICE TYPE",
    definition: "Designed to undergo processing (cleaning, disinfection, sterilization) between successive clinical uses on different patients.",
    examples: ["Stainless steel surgical retractor."]
  },
  "intended purpose": {
    category: "REGULATORY",
    definition: "The use for which a device is intended according to the data supplied by the manufacturer on the label, in the instructions for use or in promotional or sales materials.",
    examples: ["An insulin syringe specified for subcutaneous insulin delivery."]
  },
  "intended": {
    category: "REGULATORY",
    definition: "The designated clinical use or target population for which a device is engineered and certified.",
    examples: ["Intended for pediatric use."]
  },
  "classification": {
    category: "REGULATORY",
    definition: "The process of placing a medical device in a regulatory risk category based on its invasiveness, duration, and active features.",
    examples: ["Applying Rule 9 to determine Class IIb classification."]
  },
  "classify": {
    category: "REGULATORY",
    definition: "To assign a specific risk category (Class I, IIa, IIb, III) to a device using formal regulatory decision rules.",
    examples: ["Classifying a sterile syringe as Class I Sterile."]
  },
  "risk class": {
    category: "REGULATORY",
    definition: "A tier of regulatory control matching the hazard profile of a device, with Class III being the highest and Class I being the lowest risk.",
    examples: ["Class III for high-risk life-supporting implants.", "Class I for low-risk non-invasive supplies."]
  },
  "class i": {
    category: "REGULATORY",
    definition: "Low-risk medical devices subject to general regulatory controls.",
    examples: ["Manual wheelchairs.", "Stethoscopes.", "Elastic bandages."]
  },
  "class iia": {
    category: "REGULATORY",
    definition: "Medium-low risk medical devices requiring standard conformity assessments.",
    examples: ["Hearing aids.", "Surgical gloves.", "Diagnostic ultrasound machines."]
  },
  "class iib": {
    category: "REGULATORY",
    definition: "Medium-high risk medical devices requiring rigorous design and manufacturing reviews.",
    examples: ["Infusion pumps.", "Surgical lasers.", "Ventilators."]
  },
  "class iii": {
    category: "REGULATORY",
    definition: "High-risk medical devices requiring pre-market approval and extensive clinical evidence.",
    examples: ["Prosthetic heart valves.", "Implantable defibrillators.", "Coronary stents."]
  },
  "central nervous system": {
    category: "ANATOMY",
    definition: "The brain, meninges, and spinal cord. Direct contact with the CNS automatically escalates device risk to Class III in most jurisdictions.",
    examples: ["Dural repair patches.", "Brain biopsy needles.", "Intracranial pressure monitors."]
  },
  "cns": {
    category: "ANATOMY",
    definition: "Abbreviation for the Central Nervous System (brain, spinal cord, and meninges).",
    examples: ["CNS-contacting catheter."]
  },
  "circulatory system": {
    category: "ANATOMY",
    definition: "The heart and the major blood vessels (aorta, vena cava, coronary arteries, pulmonary veins, etc.). Direct contact with these structures implies Class III risk.",
    examples: ["Coronary angioplasty catheters.", "Cardiopulmonary bypass circuits."]
  },
  "circulation": {
    category: "ANATOMY",
    definition: "The movement of blood through the heart and major systemic and pulmonary vessels.",
    examples: ["Devices in direct contact with central blood circulation."]
  },
  "heart": {
    category: "ANATOMY",
    definition: "The central muscular organ that pumps blood through the circulatory system. Direct contact requires extreme regulatory scrutiny (Class III).",
    examples: ["Cardiac pacemakers.", "Heart valve prostheses."]
  },
  "medicinal product": {
    category: "REGULATORY",
    definition: "Any substance or combination of substances presented as having properties for treating or preventing disease in human beings.",
    examples: ["Heparin coating on a catheter.", "Drug-eluting coronary stents."]
  },
  "medicine": {
    category: "REGULATORY",
    definition: "A pharmacological, immunological, or metabolic substance used to treat, cure, or prevent human disease.",
    examples: ["Antibiotics infused via a syringe."]
  },
  "biological materials": {
    category: "BIOMATERIAL",
    definition: "Materials of human or animal origin incorporated into medical devices to assist with healing, remodeling, or structural support.",
    examples: ["Bovine pericardial heart valves.", "Porcine collagen wound scaffolds."]
  },
  "animal materials": {
    category: "BIOMATERIAL",
    definition: "Tissues, cells, or substances derived from animal sources used in medical devices, requiring strict TSE/BSE safety certifications.",
    examples: ["Animal-derived collagen matrices."]
  },
  "human materials": {
    category: "BIOMATERIAL",
    definition: "Tissues or cellular derivatives of human origin, such as bone grafts or skin sheets, subject to strict donor screening and processing controls.",
    examples: ["Demineralized human bone matrix."]
  },
  "sterilization": {
    category: "REGULATORY",
    definition: "A validated process used to render a product free from viable microorganisms.",
    examples: ["Ethylene oxide gas sterilization.", "Gamma radiation sterilizers."]
  },
  "disinfection": {
    category: "REGULATORY",
    definition: "Thermal or chemical processes used to reduce the number of viable microorganisms, but not necessarily bacterial spores.",
    examples: ["Disinfectant solutions for endoscopes."]
  },
  "contraceptive": {
    category: "DEVICE TYPE",
    definition: "A device or barrier intended to prevent pregnancy or conception.",
    examples: ["Intrauterine devices (IUDs).", "Condoms."]
  },
  "std": {
    category: "DEVICE TYPE",
    definition: "Sexually Transmitted Disease. Devices preventing STDs are strictly regulated to ensure reliable barrier integrity.",
    examples: ["Male and female latex condoms."]
  },
  "ionizing radiation": {
    category: "PHYSICS",
    definition: "High-energy radiation capable of liberating electrons from atoms, creating health risks that demand Class IIb/III classification.",
    examples: ["X-ray computed tomography (CT) scanners.", "Linear accelerators for oncology."]
  },
  "radiation": {
    category: "PHYSICS",
    definition: "The emission or transmission of energy in the form of waves or particles through space.",
    examples: ["Infrared light therapy.", "Ionizing X-rays."]
  },
  "active diagnostic": {
    category: "DEVICE TYPE",
    definition: "Active devices used to provide information for detecting, diagnosing, monitoring, or treating physiological conditions.",
    examples: ["Electrocardiographs (ECG).", "Clinical thermometers.", "Magnetic resonance imaging (MRI)."]
  },
  "active therapeutic": {
    category: "DEVICE TYPE",
    definition: "Active devices used to support, modify, replace, or restore biological functions or structures with the view of treating or alleviating illness or injury.",
    examples: ["Defibrillators.", "Surgical lasers.", "Electrosurgical generators."]
  },
  "regulatory": {
    category: "REGULATORY",
    definition: "Relating to official rules, directives, laws, and compliance procedures set by government bodies like the FDA, EMA, or national competent authorities.",
    examples: ["FDA 510(k) clearance.", "MDR compliance audit."]
  },
  "conformity assessment": {
    category: "REGULATORY",
    definition: "The systematic demonstration that specified requirements relating to a medical device (safety, performance, quality) are fulfilled.",
    examples: ["Notified Body audit of ISO 13485 quality systems."]
  },
  "notified body": {
    category: "REGULATORY",
    definition: "An independent third-party conformity assessment organization designated by regulatory authorities to assess medical device compliance before market placement.",
    examples: ["TÜV SÜD.", "BSI.", "DEKRA."]
  },
  "ce marking": {
    category: "REGULATORY",
    definition: "A certification mark indicating conformity with health, safety, and environmental protection standards for products sold within the European Economic Area.",
    examples: ["Affixing the CE mark with the Notified Body's 4-digit ID."]
  },
  "medical device": {
    category: "DEVICE TYPE",
    definition: "Any instrument, apparatus, software, implant, reagent, or material intended by the manufacturer to be used for diagnostic or therapeutic medical purposes.",
    examples: ["Surgical scalpel.", "Cardiac pacemaker.", "MRI machine."]
  },
  "device": {
    category: "DEVICE TYPE",
    definition: "An object, tool, or software system engineered to perform a specific physical, chemical, or computational medical operation.",
    examples: ["Infusion device."]
  },
  "absorbable": {
    category: "BIOMATERIAL",
    definition: "Capable of being degraded and safely absorbed by human tissue over time, eliminating the need for surgical removal.",
    examples: ["Absorbable sutures.", "Absorbable bone pins."]
  },
  "absorbed": {
    category: "BIOMATERIAL",
    definition: "The biological state of a material being metabolized or broken down and integrated safely into the human body's tissues.",
    examples: ["Absorbed polymer meshes."]
  },
  "bio-effect": {
    category: "BIOPHYSICS",
    definition: "The specific biological response or tissue modification induced by a medical device, which can escalate regulatory risk class.",
    examples: ["Cellular stimulation.", "Tissue ablation using radiofrequency."]
  },
  "chemotherapeutic": {
    category: "PHARMACOLOGY",
    definition: "Relating to chemical substances used to treat diseases, specifically cancer. Devices administering or storing these demand Class IIb/III classification.",
    examples: ["Chemotherapy infusion pumps.", "Port-a-caths."]
  },
  "vitals": {
    category: "CLINICAL",
    definition: "Essential physiological metrics of the human body, including heart rate, blood pressure, respiration rate, and temperature.",
    examples: ["Multi-parameter ICU monitors."]
  },
  "administering": {
    category: "CLINICAL",
    definition: "The direct physical delivery of substances (drugs, fluids, gases) or energy to a patient's body.",
    examples: ["Administering saline via volumetric pump."]
  },
  "fluid": {
    category: "CLINICAL",
    definition: "Liquids or gases channeled, stored, or administered to patients for therapeutic or hydration purposes.",
    examples: ["Intravenous saline.", "Peritoneal dialysate."]
  },
  "wound dressing": {
    category: "DEVICE TYPE",
    definition: "A sterile pad, compress, or barrier applied directly to a wound to promote healing and protect from contamination.",
    examples: ["Hydrogel dressings.", "Alginate dressings.", "Standard adhesive bandages."]
  },
  "injured skin": {
    category: "ANATOMY",
    definition: "Skin where the epidermal barrier has been breached, cut, burned, or ulcerated, making the underlying tissue vulnerable.",
    examples: ["Severe burns.", "Surgical incisions."]
  },
  "body orifice": {
    category: "ANATOMY",
    definition: "Any natural opening in the body (such as the mouth, nose, ear, urethra, vagina, or anus), as well as the external surface of the eyeball.",
    examples: ["Nasopharyngeal airways.", "Urethral catheters."]
  }
};

function findLocalDefinition(term: string): { category: string; definition: string; examples: string[] } | null {
  const normalized = term.trim().toLowerCase().replace(/[.,/#!$%^&*;:{}=\-_`~()]/g, "");
  
  // 1. Try exact match on normalized term
  if (LOCAL_GLOSSARY[normalized]) {
    return LOCAL_GLOSSARY[normalized];
  }
  
  // 2. Try match where a dictionary key is inside our normalized term (e.g., "essential parts" -> matches "essential part")
  const keysSorted = Object.keys(LOCAL_GLOSSARY).sort((a, b) => b.length - a.length);
  for (const key of keysSorted) {
    if (normalized.includes(key)) {
      return LOCAL_GLOSSARY[key];
    }
  }

  // 3. Try match where normalized term is inside a dictionary key (e.g., "implant" -> matches "implantable")
  for (const key of keysSorted) {
    if (key.includes(normalized)) {
      return LOCAL_GLOSSARY[key];
    }
  }

  return null;
}

export default function WordMeaningPopup({ term, context, position, onClose }: WordMeaningPopupProps) {
  const [loading, setLoading] = useState(true);
  const [definition, setDefinition] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!term) return;
    
    // Deselect text so it doesn't trigger again
    window.getSelection()?.removeAllRanges();

    const controller = new AbortController();
    let isMounted = true;

    const fetchDefinition = async () => {
      if (!isMounted) return;
      setLoading(true);
      setError(null);

      // Check local glossary first
      const localMatch = findLocalDefinition(term);
      if (localMatch) {
        if (isMounted) {
          setDefinition(localMatch);
          setLoading(false);
        }
        return;
      }

      const timeoutId = setTimeout(() => {
        if (isMounted) {
          controller.abort();
        }
      }, 15000); // 15 second timeout
      
      const cleanTerm = term.trim().replace(/[.,/#!$%^&*;:{}=\-_`~()]/g, "");
      const hasSpaces = cleanTerm.includes(" ");
      
      try {
        const response = await fetch('/api/define', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ term, context }),
          signal: controller.signal
        });
        clearTimeout(timeoutId);
        
        if (!isMounted) return;

        if (!response.ok) {
          throw new Error(`API status ${response.status}`);
        }
        
        const data = await response.json();
        if (isMounted) {
          setDefinition(data);
        }
      } catch (err: any) {
        clearTimeout(timeoutId);
        if (!isMounted) return;
        
        if (err.name === 'AbortError') {
          return;
        }

        console.warn("Primary definition API failed, trying public dictionary fallback...", err);
        
        // Fallback 1: Public keyless Dictionary API (ONLY if it has no spaces, to avoid 404 console errors)
        if (!hasSpaces) {
          try {
            const dictRes = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(cleanTerm)}`, {
              signal: controller.signal
            });
            if (!isMounted) return;

            if (dictRes.ok) {
              const dictData = await dictRes.json();
              if (Array.isArray(dictData) && dictData.length > 0) {
                const firstEntry = dictData[0];
                const firstMeaning = firstEntry.meanings?.[0];
                const firstDef = firstMeaning?.definitions?.[0];
                
                if (firstDef && isMounted) {
                  setDefinition({
                    category: (firstMeaning?.partOfSpeech || "Dictionary").toUpperCase(),
                    definition: firstDef.definition,
                    examples: firstDef.example ? [firstDef.example] : []
                  });
                  return;
                }
              }
            }
          } catch (dictErr: any) {
            if (dictErr.name === 'AbortError') return;
            console.warn("Public dictionary API fallback failed:", dictErr);
          }
        }

        if (isMounted) {
          // Fallback 2: Intelligent local explanation
          setDefinition({
            category: "GLOSSARY EXPLAINER",
            definition: `"${cleanTerm}" is an important term defined in medical device classification guidelines. It refers to a critical element or parameter in active or invasive device assessments.`,
            examples: [`Studying standard criteria for ${cleanTerm}.`, `Evaluating compliance parameters for ${cleanTerm}.`]
          });
        }
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    };

    fetchDefinition();

    return () => {
      isMounted = false;
      controller.abort();
    };
  }, [term, context]);

  if (!position || !term) return null;

  return (
    <div 
      className="fixed z-50 bg-white rounded-xl shadow-xl border border-slate-200 w-80 overflow-hidden flex flex-col"
      style={{
        left: `${Math.min(position.x, window.innerWidth - 340)}px`,
        top: `${Math.min(position.y + 10, window.innerHeight - 200)}px`
      }}
    >
      <div className="bg-[#0f172a] text-white px-4 py-3 flex justify-between items-center">
        <div className="flex items-center gap-2">
          <Book className="w-4 h-4 text-blue-400" />
          <h3 className="font-bold text-sm truncate">{term}</h3>
        </div>
        <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
          <X className="w-4 h-4" />
        </button>
      </div>
      
      <div className="p-4 max-h-60 overflow-y-auto">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-6 gap-2">
            <Loader2 className="w-6 h-6 text-blue-500 animate-spin" />
            <p className="text-xs text-slate-500">Looking up meaning...</p>
          </div>
        ) : error ? (
          <p className="text-sm text-red-500">{error}</p>
        ) : definition ? (
          <div>
            <span className="inline-block bg-blue-100 text-blue-800 text-xs px-2 py-1 rounded font-semibold mb-2">
              {definition.category}
            </span>
            <p className="text-sm text-slate-700 leading-relaxed mb-3">
              {definition.definition}
            </p>
            {definition.examples && definition.examples.length > 0 && (
              <div>
                <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Examples</p>
                <ul className="list-disc pl-4 space-y-1">
                  {definition.examples.map((ex: string, i: number) => (
                    <li key={i} className="text-xs text-slate-600">{ex}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ) : null}
      </div>
    </div>
  );
}
